# Generated by Django 5.0.2 on 2024-02-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_short', models.TextField()),
                ('description', models.TextField()),
                ('gold', models.IntegerField()),
                ('tags', models.CharField(blank=True, choices=[('SpellBlock', 'SpellBlock'), ('Jungle', 'Jungle'), ('Mana', 'Mana'), ('ManaRegen', 'ManaRegen'), ('LifeSteal', 'LifeSteal'), ('OnHit', 'OnHit'), ('Lane', 'Lane'), ('Tenacity', 'Tenacity'), ('CriticalStrike', 'CriticalStrike'), ('Slow', 'Slow'), ('Boots', 'Boots'), ('NonbootsMovement', 'NonbootsMovement'), ('ArmorPenetration', 'ArmorPenetration'), ('Consumable', 'Consumable'), ('SpellDamage', 'SpellDamage'), ('MagicResist', 'MagicResist'), ('Stealth', 'Stealth'), ('Vision', 'Vision'), ('MagicPenetration', 'MagicPenetration'), ('Active', 'Active'), ('SpellVamp', 'SpellVamp'), ('GoldPer', 'GoldPer'), ('Health', 'Health'), ('Aura', 'Aura'), ('Armor', 'Armor'), ('AttackSpeed', 'AttackSpeed'), ('HealthRegen', 'HealthRegen'), ('Trinket', 'Trinket'), ('Damage', 'Damage'), ('AbilityHaste', 'AbilityHaste'), ('CooldownReduction', 'CooldownReduction')], max_length=20)),
            ],
        ),
    ]
