# Generated by Django 5.0.2 on 2024-02-18 15:06

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=200, validators=[backend.models.validate_tags]),
        ),
    ]
