# Generated by Django 5.0.2 on 2024-02-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_from', to='backend.item')),
                ('into_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_into', to='backend.item')),
            ],
            options={
                'unique_together': {('from_field', 'into_field')},
            },
        ),
    ]
